script:
  - ./scripts/build.command
  - make -C middefence
install:
  - sudo apt-get update -qq
  - sudo cp -r fonts/* /usr/local/share/fonts/
  - mkdir -p ~/.fonts
  - cp -r middefence/fonts/* ~/.fonts
  - sudo fc-cache -f -v
  - sudo apt-get install texlive-full python-pygments
